config/routes.rb
Forleaders::Application.routes.draw do

  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :user, :controller => "user"
  get 'user_root' => 'dashboard#index', as: :user_root
  resources :users
  post 'edit_users', to: 'users#update'

  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/articles', to: 'dashboard#articles'

  get 'live', to: 'static_pages#live'
  get 'aovivo', to: 'static_pages#aovivo'

  localized do

      root 'static_pages#home'

      get 'individual_consultory', to:'static_pages#individual_consultory'
      get 'group_consultory', to:'static_pages#group_consultory'
      get 'the_method', to:'static_pages#the_method'
      get 'our_consultors', to: 'static_pages#our_consultors'
      get 'derose_method', to: 'static_pages#derose_method'
      get 'apply', to: 'static_pages#apply'
      get 'contact', to: 'static_pages#contact'
      get 'recommend', to: 'static_pages#recommend'
      get 'net', to: 'static_pages#net'
      get 'enterprise_testimonials', to: 'static_pages#enterprise_testimonials'
      get 'institution_testimonials', to: 'static_pages#institution_testimonials'
      get 'intense_training', to: 'static_pages#group_consultory', type: "it"
      get 'extensive_training', to: 'static_pages#group_consultory', type: "et"
      get 'leader_coaching', to: 'static_pages#group_consultory', type: "lc"
      resources :articles
  end

  match 'apply_message' => 'static_pages#apply_message', :via => :post
  match 'contact_message' => 'static_pages#contact_message', :via => :post

  resources :categories

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :can_use_dashboard
  layout "users"

  def articles
    @root_articles = ArticleLanguage.joins(:articles).uniq.order('created_at DESC').page(params[:page]).per(6)
  end

  def authors
    @authors = Author.page(params[:page]).per(6)
  end

  def index
    @user = current_user
  end

  private

  def can_use_dashboard
    if !user_signed_in? || !current_user.role?("author")
      flash[:warning] = "You do not have sufficient privileges to use the dashboard"
      redirect_to user_root_path
    end
  end
end

app/views/dashboard/_article.html.erb
<div class="row">
  <div class="col-md-5">
    <%= image_tag article.article_image, width: "100%" %>
  </div>
  <div class="col-md-7">
    <div class="row">
      <div class="col-md-12">
        <h2><%= article.title %></h2>
        <h3><%= article.subtitle %></h3>
        <p><%= article.excerpt %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h2>Languages</h2>
        <% article.article_language.articles.each do |art| %>
          <%= link_to article_path(art.id), class: "btn btn-default" do %>
            <%= art.lang %>
          <% end %>
        <% end %>
        <% if article.article_language.missing_languages.count != 0 %>
          <h2>Translate to:</h2>
          <% article.article_language.missing_languages.each do |lang| %>
            <%= link_to new_article_path(article_language: article.article_language.id, lang: lang), class: "btn btn-default" do %>
              <%= lang %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/articles.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= paginate @root_articles %>  
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <% @root_articles.each do |root_article| %>
        <%= render "dashboard/article", article: root_article.articles.first unless root_article.articles.empty? %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= paginate @root_articles %>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>Hello <%= current_user.email %>! </br></h2>
      <%= link_to "Edit my data", edit_user_registration_path %>
    </div>
  </div>
  <div class="row" data-no-turbolink>
    <div class="col-md-12">
      <h3>Actions</h3>
      <% if (current_user.role? 'author') %>
        <h4>Articles</h4>
        <%= link_to "Add new article", new_article_path %><br>
        <%= link_to "View articles", dashboard_articles_path %>
      <% end %>
      <% if current_user.admin? %>
      <h3>Admin panel</h3>
      <%= link_to "Go to admin panel", user_index_path %>
      <% end %>
    </div>
  </div>
</div>