config/routes.rb
Forleaders::Application.routes.draw do

  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :user, :controller => "user"
  get 'user_root' => 'dashboard#index', as: :user_root
  resources :users
  post 'edit_users', to: 'users#update'

  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/articles', to: 'dashboard#articles'

  get 'live', to: 'static_pages#live'
  get 'aovivo', to: 'static_pages#aovivo'

  localized do

      root 'static_pages#home'

      get 'individual_consultory', to:'static_pages#individual_consultory'
      get 'group_consultory', to:'static_pages#group_consultory'
      get 'the_method', to:'static_pages#the_method'
      get 'our_consultors', to: 'static_pages#our_consultors'
      get 'derose_method', to: 'static_pages#derose_method'
      get 'apply', to: 'static_pages#apply'
      get 'contact', to: 'static_pages#contact'
      get 'recommend', to: 'static_pages#recommend'
      get 'net', to: 'static_pages#net'
      get 'enterprise_testimonials', to: 'static_pages#enterprise_testimonials'
      get 'institution_testimonials', to: 'static_pages#institution_testimonials'
      get 'intense_training', to: 'static_pages#group_consultory', type: "it"
      get 'extensive_training', to: 'static_pages#group_consultory', type: "et"
      get 'leader_coaching', to: 'static_pages#group_consultory', type: "lc"
      resources :articles
  end

  match 'apply_message' => 'static_pages#apply_message', :via => :post
  match 'contact_message' => 'static_pages#contact_message', :via => :post

  resources :categories

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout "static_pages"
  caches_page :home, :individual_consultory, :group_consultory, :our_consultors,
              :derose_method, :institution_testimonials, :enterprise_testimonials,
              :apply, :apply_message, :contact, :contact_message, :recommend,
              :net

  def home
    if user_signed_in? && !current_user.nil? && (current_user.role? "translator") && ((current_user.debug_translations == "missing") || (current_user.debug_translations == "all"))
      expire_fragment('home')
    end
    lang = params[:locale] ? params[:locale] : I18n.locale
    @articles = Article.includes(:categories).where("lang = ? AND publish_at <= ?", lang, DateTime.now).page(1).per(6)
    @articles_number = @articles.count
    @articles_columns = 3
    @articles_rows =  @articles.count > 3 ? 2 : 1
  end

  def individual_consultory
    if user_signed_in? && !current_user.nil? && (current_user.role? "translator") && ((current_user.debug_translations == "missing") || (current_user.debug_translations == "all"))
      expire_fragment('individual_consultory')
    end
  end

  def group_consultory
    if user_signed_in? && !current_user.nil? && (current_user.role? "translator") && ((current_user.debug_translations == "missing") || (current_user.debug_translations == "all"))
      expire_fragment('group_consultory')
    end
  end

  def the_method
  end

  def our_consultors
    if user_signed_in? && !current_user.nil? && (current_user.role? "translator") && ((current_user.debug_translations == "missing") || (current_user.debug_translations == "all"))
      expire_fragment('our_consultors')
    end
  end

  def derose_method
    if user_signed_in? && !current_user.nil? && (current_user.role? "translator") && (!current_user.debug_translations.blank?)
      expire_fragment('derose_method')
    end
  end

  def institution_testimonials
    if user_signed_in? && !current_user.nil? && (current_user.role? "translator") && ((current_user.debug_translations == "missing") || (current_user.debug_translations == "all"))
      expire_fragment('institution_testimonials')
    end
  end

  def enterprise_testimonials
    if user_signed_in? && !current_user.nil? && (current_user.role? "translator") && ((current_user.debug_translations == "missing") || (current_user.debug_translations == "all"))
      expire_fragment('enterprise_testimonials')
    end
  end

  def apply
    @apply_message = ApplyMessage.new
  end

  def apply_message
    @apply_message = ApplyMessage.new(params[:apply_message])

    if @apply_message.valid?
      ApplyMailer.new_apply_form(@apply_message).deliver
      redirect_to apply_url, notice: "Message sent. Thank you for contacting us."
    else
      redirect_to apply_url, notice: "Please fill all required fields."
    end
  end

  def contact
    @contact_message = ContactMessage.new
  end

  def recommend
    @contact_message = ContactMessage.new
  end

  def contact_message
    @contact_message = ContactMessage.new(params[:contact_message])

    if @contact_message.valid? && verify_recaptcha(model: @contact_message)
      ContactMailer.new_contact_form(@contact_message).deliver
      redirect_to root_url, notice: "Message sent. Thank you for contacting us."
    else
      redirect_to contact_url, notice: "Please fill all required fields."
    end
  end

  def net
    if user_signed_in? && !current_user.nil? && (current_user.role? "translator") && ((current_user.debug_translations == "missing") || (current_user.debug_translations == "all"))
      expire_fragment('net')
    end
  end

  def live
    redirect_to "https://www.youtube.com/metododerose", :status => 301
  end

  def aovivo
    redirect_to "https://www.youtube.com/metododerose", :status => 301
  end
end

app/views/static_pages/_article_container.html.erb
<div class="row articles-container">
  <% columns.times do |column| %>
    <%= render 'single_article', article: articles[first_article_number + column] unless @articles_number <= first_article_number + column%>
  <% end %>
</div>

app/views/static_pages/_articles.html.erb
<div class="row padding-topbottom-50">
  <div class="col-md-10 col-sm-12 col-md-offset-1">
      <div class="row articles-title-container">
        <div class="col-md-6 col-sm-6">
          <div class="home-section-title">
            <%= t('static_pages.articles.title') %>
          </div>
          <div class="home-section-subtitle">
            <%= t('static_pages.articles.subtitle') %>
          </div>
        </div>
        <!-- div class="col-md-3 col-md-offset-3 articles-selector-container">
          <ul class="nav" id="article-selector-title">
            <li class="dropdown articles-selector-container-item">
              <a class="dropdown-toggle articles-selector" data-toggle="dropdown" href="#">
                CATEGORIAS
              </a>
              <ul class="dropdown-menu" id="articles-selector-items">
                <li class="articles-category-leadership">
                  <a href="#">LIDERANÇA</a>
                </li>
                <li class="articles-category-high_performance">
                  <a href="#">ALTA PRODUTIVIDADE</a>
                </li>
                <li class="articles-category-focus">
                  <a href="#">FOCO</a>
                </li>
                <li class="articles-category-intuition">
                  <a href="#">INTUIÇão aplicada</a>
                </li>
                <li class="articles-category-human_relationships">
                  <a href="#">Relação interpessoal</a>
                </li>
                <li class="articles-category-quality_of_life">
                  <a href="#">QUALIDADE DE VIDA</a>
                </li>
              </ul>
            </li>
          </ul>
        </div -->
      </div>

      <div class="row articles-container">
        <% @articles.each do |article| %>
          <%= render 'single_article', article: article %>
        <% end %>
      </div>

      <!-- div class="row more-articles">
        <a href="#">
          <span class="glyphicon glyphicon-plus-sign"></span>
        </a>
      </div -->
  </div>
</div>

app/views/static_pages/_individual_consultory_consultory.pt.html.erb
    <h2>CONTEÚDO</h2>
    <p>Este programa foi desenvolvido para responder aos desafios dos Presidentes, CEOs e Altos Executivos. O conteúdo das consultorias é altamente profundo e individualizável. O seu <i>Consultor Expert</i> moldará o serviço de acordo com os seus interesses, expectativas e necessidades.</p>

    <h2>FREQUÊNCIA E DURAÇÃO</h2>
    <p>Frequência: 1 encontro semanal
        Passível de adaptações</p>
    <p>Duração: 3 a 6 meses</p>
    <p>Observação: a consultoria pode ser combinada com Personal Teaching ou Treinamento</p>

    <h2>CONSULTORES EXPERTS</h2>
    <p>Todas as consultorias são ministradas exclusivamente pelos nossos <i>Consultores Experts</i>. Além de muito conhecimento técnico e de uma excelência em ensinar ferramentas para o aprimoramento pessoal, eles têm uma experiência de vida que os permite oferecer um olhar externo sobre a rotina e os hábitos do executivo com o propósito de catapultar a sua evolução e seu nível de realização. Todos eles contam com mais de 15 anos de ensino, têm ministrado consultorias e palestras em vários países e são considerados os melhores profissionais nas suas respectivas áreas.</p>

    <h2>LOCAL</h2>
    <p>Presencial nas cidades com Consultores Experts</p>
    <p>O acompanhamento será feito no local mais conveniente para você: na empresa, em casa ou nos estabelecimentos do M<span class='navbar-title-smallcaps'>ÉTODO</span> DeR<span class='navbar-title-smallcaps'>OSE</span></p>
    <p>On-line em qualquer lugar do mundo</p>

    <h2>METODOLOGIA</h2>
    <p>Os temas da consultoria são escolhidos em função das suas necessidades. Cada consultor desenvolveu áreas de conhecimento específicas. Escolheremos o consultor que responderá melhor às suas expectativas.</p>
    <p>Os encontros com os nossos Consultores Experts acontecerão uma vez por semana. Fora desses momentos, o consultor está comprometido a orientar e aconselhar o líder de sempre que houver disponibilidade. Ele o acompanhará de perto e transmitirá uma grande quantidade de conhecimento prático para o seu desenvolvimento pessoal e profissional.</p>

    <h2>PORQUE INVESTIR EM UMA CONSULTORIA?</h2>
    <p>Chega um momento na carreira de grandes líderes em que já se conquistou muito sucesso e que é preciso mais para ir além. Nesse ponto o contato com um outro ponto de vista permitirá atingir outros patamares de realização pessoal e de performance profissional. O que faz a diferença não são mais os números e os processos operacionais, e sim o porquê estamos trabalhando, onde queremos chegar e como o faremos. O valor de um acompanhamento personalizado que promove o despertamento e desenvolvimento de novas aptidões e faculdades é inestimável.</p>

app/views/static_pages/_individual_consultory_small_group_teaching.fr.html.erb
    <h2>CONTENU</h2>
    <p>50 minutes de cours pratique : définition musculaire, augmentation de la vitalité et de la capacité respiratoire, amélioration de la concentration, développement de l'intuition, etc.  </p>
    <p>10 minutes de cours théorique : productivité, gestion du stress, résolution des conflits, alimentation, gestion du temps, relations interpersonnelles...</p>
    <p>Newsletter hebdomadaire sur la Haute Performance Professionnelle.</p>
    
    <h2>FREQUENCE ET DURÉE</h2>
    <p>Fréquence : de un à sept jours par semaine</p>
    <p>Durée minimal : 3 mois</p>
    <p>L'objectif est de développer vos capacités sur le long terme. Vos résultats dépenderont donc principalement de votre discipline et la régularité de vos entrainements.</p>
    
    <h2>PARTICIPANTS</h2>
    <p>Maximum de 15 leaders</p>

    <h2>LIEU</h2>
    <p>En direct dans toutes les villes de nos Personal Teachers. (Contactez-nous pour plus d'informations)</p>
    <p>Vous pouvez choisir le lieu dans lequel les cours vous sont donnés : au sein de votre entreprise, à domicile ou dans nos établissements DeR<span class="navbar-title-smallcaps">OSE</span>.</p>
    <p>Via internet dans le monde entier</p>

    <h2>MÉTODOLOGIE</h2>
    <p>"Le Small Group Teaching constitue le meilleure programme pour entrainer une équipe de façon efficace et durable. 
    Il permet en effet de développer le potentiel des leaders au niveau physique, émotionnel, mental. La partie pratique de 50 minutes est idéale pour stimuler la vitalité, devenir plus productif et mieux gérer le stress de façon durable. Les 10 minutes de conversation permettent ensuite d'établir des objectifs précis et d'apprendre des outils concrets pour améliorer le quotidien. En dehors des horaires de cours, le Personal professeur est également à votre écoute des leaders pour répondre à leurs questions. Il peut également leur proposer des exercices et des lectures qui réponderont à leurs besoins. Ils receveront une newsletter hebdomadaire contenant des textes de grande qualité rédigés par nos Consultants Experts. Ils pourront ainsi s'approfondir sur des thèmes variés tels que le leadership, la productivité au travail, les relations interpersonnelles, la qualité de vie, le bien-être, la gestion du stress et la concentration."</p>

    <h2>CERTAINS DES RÉSULTATS PERÇUS</h2>
    <p><strong>Dans les premiers mois:</strong></p>
    <p>Amélioration de la gestion du stress</p>
    <p>Augmentation de la capacité pulmonaire</p>
    <p>Tonus musculaire</p>
    <p>Plus de Souplesse</p>
    <p>Amélioration de la  concentration</p>
    <p>Meilleure capacité de décontraction</p>
    <p>Stabilité émotionnelle</p>
    <p>Meilleure capacité de repos</p>
    <p>Plus haut niveau de vitalité</p>
    <p>Amélioration globale de la qualité de vie</p>
    <br>
    <p><strong>Après quelques mois de pratique régulière:</strong></p>
    <p>Développement du leadership</p>
    <p>Développement de l'intuition</p>
    <p>Plus de créativité</p>
    <p>Meilleure résolution des conflits</p>
    <p>Meilleure gestion d'équipe</p>
    <p>Augmentation de la productivité</p>
    <p>Plus grande réalisation personnelle</p>

app/views/static_pages/_individual_consultory_small_group_training.fr.html.erb
    <h2>MODALITÉS</h2>
    <p>Conférences : de 1 à 4 heures</p>
    <p>Formations : 1, 2 ou 5 jours <br>
    les formations sont limitées à 20 participants.</p>
    <p>Lieu : Dans les locaux de l'entreprise ou dans nos établissements.</p>

    <h2>FORMATIONS SUR MESURE</h2>
    <p>Nous construisons nos formations sur mesure en fonction de vos attentes.</p> 
    <p>Nous pouvons ainsi vous orienter pour choisir les thèmes, les intervenants et la durée qui seront le plus profitables à vos équipes.</p>
    
    <h2>EXEMPLES DE FORMATIONS PROPOSÉES</h2>
    <p>Réservées aux cadres dirigeants :</p>
    <p><b>"Les clés pour développez des relations humaines productives."</b></p>
    <p><b>"Savoir anticiper et résoudre les conflits."</b></p>
    <p><b>"Prévenir le stress et les burnouts de ses équipes."</b></p>
    <p><b>"Concentration et Intuition : les nouveaux outils des leaders de demain."</b></p>
    <br>
    <p>Autour du développement professionnel :</p>
    <p><b>"Prévenir l'excès de stress et apprendre à le gérer."</b></p>
    <p><b>"Savoir se concentrer - la clé de l'efficacité."</b></p>
    <p><b>"10 outils pour optimisez votre efficacité au quotidien."</b></p>
    <p><b>"Gérez mieux votre temps… Travaillez plus intelligement."</b></p>
    <br>
    <p>Autour du développement personnel :</p>
    <p><b>"Qualité de vie : la clé d'une performance sur le long terme."</b></p>
    <p><b>"Les émotions : ne plus les subir et savoir les utiliser en votre faveur."</b></p>
    <p><b>"Les clés d'une bonne préparation physique et mentale."</b></p>
    <p><b>"Savoir cultiver d'excellentes relations interpersonnelles."</b></p>
    <br>
    <p>Contactez-nous pour obtenir le programme détaillé ainsi que les modalités d'une de ces formations. </p>

    <h2>MÉTHODOLOGIE</h2>
    <p>Les Formations intensives permettent d'aborder un thème spécifique aussi bien sur le plan théorique que pratique. Elles ont pour objectif de provoquer une prise de conscience ouvrant la possibilité de changements d'attitude et de comportement au travail. Elles constituent un temps d'apprentissage intensif permettant de développer les capacités de chacun tout en renforçant la cohésion de l'équipe. Les participants pourront ensuite être accompagnés en suivant nos programmes de Formations extensives ou de Coaching afin que cet apprentissage s'intégre efficacement dans leur quotidien.</p>

    <h2>FORMATEURS</h2>
    <p>Toutes nos formations sont conduites par nos consultants les plus expérimentés. Ces derniers possèdent une longue expérience d'enseignement et accompagnent au quotidien de grands dirigeants dans leur évolution. Ils donnent des formations et des conférences à l'international et sont considérés comme les meilleurs spécialistes dans leurs domaines d'expertise.</p>

app/views/static_pages/_individual_consultory_training.es.html.erb
    <h2>CONTENIDO</h2>
    <p>Entrenamiento de <strong>15 minutos</strong> de técnicas respiratorias, corporales, de descontracción muscular y de concentración mental;</p>
    <p>Las técnicas se eligen a medida, en función de las necesidades <strong>del momento</strong>.</p>
    <p><strong>Newsletter</strong> semanal sobre Calidad de Vida y Alta Performance.</p>
    
    <h2>FRECUENCIA Y DURACIÓN</h2>
    <p><strong>Frecuencia</strong>: la parte técnica se transmite de lunes a viernes o con la periodicidad que prefiera el contratante.</p>
    <p><strong>Período mínimo</strong>: 3 meses</p>

    <h2>LUGAR</h2>
    <p>Presencial en las ciudades con Personal Teachers;</p>
    <p>Las clases se dictan en el lugar más adecuado para usted: en su empresa, en su casa o en los establecimientos del M<span class='navbar-title-smallcaps'>ÉTODO</span> DeR<span class='navbar-title-smallcaps'>OSE</span>.</p>
    <p><strong>On-line</strong> en qualquier lugar del mundo.</p>

    <h2>METODOLOGÍA</h2>
    <p>El entrenamiento de 15 minutos funciona como un Pit-Stop en que usted recarga su nivel de energía. En cada sesión el consultor elegirá las técnicas que respondan a sus necesidades del momento. Será la ocasión de aprender técnicas para aumentar la vitalidad en poquísimo tiempo, descontraerse profundamente, administrar su estrés, entrenar su concentración y capacidad de foco.</p>
    <p>Siempre que haya oportunidad, el instructor transmitirá la cultura comportamental que ha tornado al M<span class='navbar-title-smallcaps'>ÉTODO</span> DeR<span class='navbar-title-smallcaps'>OSE</span> proverbialmente conocido por su eficiencia en preparar para las buenas relaciones humanas en el trabajo y fuera de él.</p>
    <p>Este entrenamiento diario puede ser usado para complementar las clases de Personal Teaching. El líder podrá por ejemplo tener Personal Teaching de una hora semanal y entrenamientos de 15 mintuos diarios. Recordamos que la regularidad en el entrenamiento de nuestras herramientas es esencial para obtener resultados significativos.</p>


    <h2>ALGUNOS RESULTADOS DETECTADOS</h2>
    <p><strong>En los primeros meses:</strong></p>
    <p>Mejora en la administración del estrés</p>
    <p>Aumento de la capacidad pulmonar</p>
    <p>Tono muscular</p>
    <p>Flexibilidad</p>
    <p>Concentración</p>
    <p>Capacidad de descontración</p>
    <p>Estabilidad emocional</p>
    <p>Calidad del descanso</p>
    <p>Nivel de vitalidad</p>
    <p>Mejora general en la calidad de vida</p>
    <br>
    <p><strong>Después de algunos meses de práctica regular:</strong></p>
    <p>Incremento de la capacidad de liderazgo</p>
    <p>Mejora del nivel de intuición</p>
    <p>Más creatividad</p>
    <p>Mejora en la capacidad de administración de conflictos</p>
    <p>Perfeccionamiento en la gestión de personas</p>
    <p>Aumento de la productividad</p>
    <p>Crecimiento personal y organizacional</p>

app/views/static_pages/_individual_sidebar_peugeot_testimony.html.erb
<hr/>
<div class="individual-sidebar-container container peugeot-container">
  <div class="row individual-sidebar-title">
    <h1><%= t('static_pages.sidebar.peugeot.title') %></h1>
  </div>
  <div class="row individual-sidebar-body" id="peugeot_testimony">
    <div class="col-md-5">
      <div>
        <%= image_tag "erwin_museur.jpg" %>
      </div>
      <%= t('static_pages.sidebar.peugeot.erwin_data_html') %>
      </div>
    <div class="col-md-7" id="peugeot_testimony_text">
      <%= t('static_pages.sidebar.peugeot.testimonial') %>
      
    </div>
  </div>
  <div class="row pull-right individual-consultors-button-link" id="individual-testimony-button-link">
    <span>
      <a href="enterprise_testimonials"><%= t('static_pages.sidebar.peugeot.see_more') %></a>
    </span>
  </div>
</div>

app/views/static_pages/_programmes.html.erb
<div class="row programme-container padding-topbottom-50">
  <div class="col-sm-4 col-md-3 col-md-offset-1">
    <div class="home-section-title">
      <%= t('static_pages.programs.title') %>
    </div>
    <div class="home-section-subtitle">
      <%= t('static_pages.programs.subtitle') %>
    </div>
  </div>
  <div class="col-sm-8 col-md-7 subprogramme-container">
      <div class="row">
        <div class="col-sm-4 col-md-4">
          <div class="hover-gold">
            <%= link_to intense_training_path do %>
              <div class="programme-subheader">
                <%= t('static_pages.programs.enterprise.small_group_training.title') %>
              </div>
              <div class="programme-subsubheader">
                <% t('static_pages.programs.enterprise.small_group_training.subtitle') %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="col-sm-4 col-md-4">
          <div class="hover-gold">
            <%= link_to extensive_training_path do %>
              <div class="programme-subheader">
                <%= t('static_pages.programs.enterprise.talks.title') %>
              </div>
              <div class="programme-subsubheader">
                <% t('static_pages.programs.enterprise.talks.subtitle') %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="col-sm-4 col-md-4">
          <div class="hover-gold">
            <%= link_to leader_coaching_path do %>
              <div class="programme-subheader">
                <%= t('static_pages.programs.enterprise.workshop.title') %>
              </div>
              <div class="programme-subsubheader">
                <% t('static_pages.programs.enterprise.workshop.subtitle') %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/static_pages/_recommend_body.html.erb
<div class="container padding-topbottom-50">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="row" style="position:relative">
          <div class="col-md-12">
              <div class="page-title">
                <%= t('static_pages.recommend.title').html_safe %>
              </div>
              <div class="page-main-body">
                <% t('static_pages.recommend.message') %>
              </div>
          </div>
        </div>
        <div class="row contact-form">
          <div class="col-md-8">
              <div class="contact-form">
                <%= render 'recommend_form' %>
              </div>
          </div>
          <div class="col-md-4 individual-sidebar">
            <div class="row">
              <div class="col-md-12">
                <div class="">
                  <div class="recommend-sidebar-titles-title">
                    <h1><%= t('recommend.sidebar.title') %> </h1>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="recommend-sidebar-container">
                  <div class="recommend-sidebar-title">
                    <h1><%= t('recommend.sidebar.talks_and_workshops.title') %> </h1>
                  </div>
                  <div class="recommend-sidebar-body">
                    <%= t('recommend.sidebar.talks_and_workshops.body') %>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="recommend-sidebar-container">
                  <div class="recommend-sidebar-title">
                    <h1> <%= t('recommend.sidebar.individual_and_group.title') %> </h1>
                  </div>
                  <div class="recommend-sidebar-body">
                    <%= t('recommend.sidebar.individual_and_group.body') %>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="recommend-sidebar-container">
                  <div class="recommend-sidebar-title">
                    <h1> <%= t('recommend.sidebar.coaching.title') %> </h1>
                  </div>
                  <div class="recommend-sidebar-body">
                    <%= t('recommend.sidebar.coaching.body') %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/static_pages/_recommend_form.html.erb
<div class="container new-recommend-form-container">
  <div class="row recommend-form">
    <%= form_for @contact_message, url: contact_message_url, html: {role: 'form'} do |f| %>
      <% if @contact_message.errors.any? %>
        <div class="error_messages">
          <h2><%= pluralize(@contact_message.errors.count, "error") %> prohibited this message from being saved:</h2>
          <ul>
          <% @contact_message.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= label(:contact_message, :first_name) %>
          <%= f.text_field :first_name, class: 'form-control', id: 'contact_first_name' %>
      </div>
      <div class="form-group">
        <%= label(:contact_message, :last_name) %>
          <%= f.text_field :last_name, class: 'form-control', id: 'contact_last_name' %>
      </div>
      <div class="form-group">
        <%= label(:contact_message, :email) %>
          <%= f.text_field :email, class: 'form-control', id: 'contact_email' %>
      </div>
      <div class="form-group">
        <%= label(:contact_message, :school) %>
          <%= f.text_field :school, class: 'form-control', id: 'contact_position' %>
      </div>
      <div class="form-group">
        <%= label(:contact_message, :company) %>
          <%= f.text_field :company, class: 'form-control', id: 'contact_company' %>
      </div>
      <div class="form-group">
        <%= label(:contact_message, :observations) %>
          <%= f.text_area :observations, class: 'form-control', id: 'contact_observations' %>
      </div>
      <div class="form-group">
          <%= f.submit "#{t('helpers.label.recommend_message.submit')}", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/static_pages/_single_article.html.erb
<div class="col-md-4 col-sm-6 home-single-article-container">
    <div class="home-article-thumb">
      <% if article.image %>
        <%= link_to article_path(article.id) do %>
          <%= image_tag "ajax-loader.gif", class: "lazyload", data: {src: article.image.url} %>
          <% if !article.hover_frase.blank? %>
            <div class="home-article-hover-frase">
              <%= article.hover_frase %>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <div class="home-article-category">
        <div class="article-square articles-category-<%= article.categories.first.name.parameterize.underscore %>">
        </div>
        <%= link_to t("static_pages.categories.#{article.categories.first.name.parameterize.underscore}").mb_chars.upcase, category_path(article.categories.first.id)  %>
      </div>
    </div>
    <div class="home-article-title">
      <%= link_to article_path(article.id) do %>
        <%= article.title %>
      <% end %>
    </div>
    <div class="home-article-subtitle">
      <%= link_to article_path(article.id) do %>
        <%= article.subtitle %>
      <% end %>
    </div>
    <div class="home-article-author">
      <%= article.author %>
    </div>
    <div class="home-article-content">
      <%= article.excerpt %>
    </div>
    <div class="home-article-read-more">
      <%= link_to t('static_pages.articles.read_more'), article_path(article.id) %>
    </div>
</div>

app/views/static_pages/individual_consultory.html.erb
<% title "Programas individuais" %>
  <%= render 'individual_consultory_header' %>
  <%= render 'individual_consultory_body' %>

<script type="text/javascript">
  $(function() {
    // Javascript to enable link to tab
    var url = document.location.toString();
    if (url.match('#')) {
      $('.nav-pills a[href=#'+url.split('#')[1]+']').tab('show') ;
    }

    // Change hash for page-reload
    $('a[data-toggle="tab"]').on('show.bs.tab', function (e) {
      window.location.hash = e.target.hash;
    });
  });
</script>

app/views/static_pages/recommend.html.erb
<% 
  meta title: normalize_title(t('static_pages.navbar.recommend.title_html')),
        description: t('static_pages.metatags.recommend.description'),
        og: {
          description: t('static_pages.metatags.recommend.description'),
          image: "http://www.deroseforleaders.com/assets/logo_derose_method.png",
          url: recommend_url,
          title: (normalize_title(t('static_pages.navbar.recommend.title_html')))
        },
        twitter: {
          card: "summary",
          description: t('static_pages.metatags.recommend.description'),
          site: "@deroseforleaders",
          image: "http://www.deroseforleaders.com/assets/logo_derose_method.png"
        }
%>
<%= render 'recommend_header' %>
<%= render 'recommend_body' %>