config/routes.rb
Forleaders::Application.routes.draw do

  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :user, :controller => "user"
  get 'user_root' => 'dashboard#index', as: :user_root
  resources :users
  post 'edit_users', to: 'users#update'

  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/articles', to: 'dashboard#articles'

  get 'live', to: 'static_pages#live'
  get 'aovivo', to: 'static_pages#aovivo'

  localized do

      root 'static_pages#home'

      get 'individual_consultory', to:'static_pages#individual_consultory'
      get 'group_consultory', to:'static_pages#group_consultory'
      get 'the_method', to:'static_pages#the_method'
      get 'our_consultors', to: 'static_pages#our_consultors'
      get 'derose_method', to: 'static_pages#derose_method'
      get 'apply', to: 'static_pages#apply'
      get 'contact', to: 'static_pages#contact'
      get 'recommend', to: 'static_pages#recommend'
      get 'net', to: 'static_pages#net'
      get 'enterprise_testimonials', to: 'static_pages#enterprise_testimonials'
      get 'institution_testimonials', to: 'static_pages#institution_testimonials'
      get 'intense_training', to: 'static_pages#group_consultory', type: "it"
      get 'extensive_training', to: 'static_pages#group_consultory', type: "et"
      get 'leader_coaching', to: 'static_pages#group_consultory', type: "lc"
      resources :articles
  end

  match 'apply_message' => 'static_pages#apply_message', :via => :post
  match 'contact_message' => 'static_pages#contact_message', :via => :post

  resources :categories

end

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>