config/routes.rb
Forleaders::Application.routes.draw do

  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :user, :controller => "user"
  get 'user_root' => 'dashboard#index', as: :user_root
  resources :users
  post 'edit_users', to: 'users#update'

  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/articles', to: 'dashboard#articles'

  get 'live', to: 'static_pages#live'
  get 'aovivo', to: 'static_pages#aovivo'

  localized do

      root 'static_pages#home'

      get 'individual_consultory', to:'static_pages#individual_consultory'
      get 'group_consultory', to:'static_pages#group_consultory'
      get 'the_method', to:'static_pages#the_method'
      get 'our_consultors', to: 'static_pages#our_consultors'
      get 'derose_method', to: 'static_pages#derose_method'
      get 'apply', to: 'static_pages#apply'
      get 'contact', to: 'static_pages#contact'
      get 'recommend', to: 'static_pages#recommend'
      get 'net', to: 'static_pages#net'
      get 'enterprise_testimonials', to: 'static_pages#enterprise_testimonials'
      get 'institution_testimonials', to: 'static_pages#institution_testimonials'
      get 'intense_training', to: 'static_pages#group_consultory', type: "it"
      get 'extensive_training', to: 'static_pages#group_consultory', type: "et"
      get 'leader_coaching', to: 'static_pages#group_consultory', type: "lc"
      resources :articles
  end

  match 'apply_message' => 'static_pages#apply_message', :via => :post
  match 'contact_message' => 'static_pages#contact_message', :via => :post

  resources :categories

end

app/views/layouts/_advanced_toolbar.html.erb
<div id="wysihtml5-toolbar">
  <div class="block">
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="bold" title="CTRL+B">bold</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="italic" title="CTRL+I">italic</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="underline" title="CTRL+U">underline</a>
  </div>
  <div class="block">
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="createLink">link</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="removeLink"><s>link</s></a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="insertImage">image</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h1">h1</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h2">h2</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h3">h3</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="p">p</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="pre">pre</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="formatBlock" data-wysihtml5-command-blank-value="true">plaintext</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="insertBlockQuote">blockquote</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="formatCode" data-wysihtml5-command-value="language-html">Code</a>
  </div>
  
  <div class="block">
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="fontSizeStyle">Size</a>
    <div data-wysihtml5-dialog="fontSizeStyle" style="display: none;">
      Size:
      <input data-wysihtml5-dialog-field="size" style="width: 60px;" value="" type="text">
      <a data-wysihtml5-dialog-action="save">OK</a>&nbsp;<a data-wysihtml5-dialog-action="cancel">Cancel</a>
    </div>
  </div>
  
  <div class="block">
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="insertUnorderedList">• List</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="insertOrderedList">1. List</a>
  </div>
  <div class="block">
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="outdentList">&lt;-</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="indentList">-&gt;</a>
  </div>

  <div class="block">
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="alignLeftStyle">alignLeft</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="alignRightStyle">alignRight</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="alignCenterStyle">alignCenter</a>
  </div>

  <div class="block">
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="foreColorStyle">Color</a>
    <div data-wysihtml5-dialog="foreColorStyle" style="display: none;">
      Color:
      <input data-wysihtml5-dialog-field="color" value="rgba(0,0,0,1)" type="text">
      <a data-wysihtml5-dialog-action="save">OK</a>&nbsp;<a data-wysihtml5-dialog-action="cancel">Cancel</a>
    </div>
  </div>
  
  <div class="block">
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="bgColorStyle">BG Color</a>
    <div data-wysihtml5-dialog="bgColorStyle" style="display: none;">
      Color:
      <input data-wysihtml5-dialog-field="color" value="rgba(0,0,0,1)" type="text">
      <a data-wysihtml5-dialog-action="save">OK</a>&nbsp;<a data-wysihtml5-dialog-action="cancel">Cancel</a>
    </div>
  </div>
  
  <div class="block">
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="undo">undo</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="redo">redo</a>
  </div>

  <!--div class="block">
    <a data-wysihtml5-action="showSource">HTML</a>
  </div-->

  <div class="block" data-wysihtml5-hiddentools="table" style="display: none;">
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="mergeTableCells">Merge</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="addTableCells" data-wysihtml5-command-value="above">row-before</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="addTableCells" data-wysihtml5-command-value="below">row-after</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="addTableCells" data-wysihtml5-command-value="before">col-before</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="addTableCells" data-wysihtml5-command-value="after">col-after</a>
  
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="deleteTableCells" data-wysihtml5-command-value="row">delete row</a>
    <a unselectable="on" href="javascript:;" data-wysihtml5-command="deleteTableCells" data-wysihtml5-command-value="column">delete col</a>
  
  </div>


  <div data-wysihtml5-dialog="createLink" style="display: none;">
    <label>
      Link:
      <input data-wysihtml5-dialog-field="href" value="http://">
    </label>
    <a data-wysihtml5-dialog-action="save">OK</a>&nbsp;<a data-wysihtml5-dialog-action="cancel">Cancel</a>
  </div>
  <div data-wysihtml5-dialog="insertImage" style="display: none;">
    <label>
      Image:
      <input data-wysihtml5-dialog-field="src" value="http://">
    </label>
    <label>
      Align:
      <select data-wysihtml5-dialog-field="className">
        <option value="">default</option>
        <option value="wysiwyg-float-left">left</option>
        <option value="wysiwyg-float-right">right</option>
      </select>
    </label>
    <a data-wysihtml5-dialog-action="save">OK</a>&nbsp;<a data-wysihtml5-dialog-action="cancel">Cancel</a>
  </div>

</div>  

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52634314-1', 'www.deroseforleaders.com');
  ga('require', 'displayfeatures');
  ga('require', 'linkid', 'linkid.js');
  ga('send', 'pageview');

</script>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row footer-container">
    <div class="footer-inner-container">
      <div class="col-md-10 col-md-offset-1">
        <div class="row">
          <div class="col-md-4 gold-color footer-title">
            <%= t('static_pages.footer.title_html') %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 footer-inner-column">
            <div class="after-title gold-color inner-footer-title"><%= t('static_pages.footer.derose_for_leaders.title') %></div>
            <div class="inner-footer-content border-9">
              <%= link_to t('static_pages.footer.derose_for_leaders.derose_method_html'), derose_method_path, class: "inner-footer-link"%>
              <%= link_to t('static_pages.footer.derose_for_leaders.personal_teachers'), our_consultors_path, class: "inner-footer-link"%>
              <%= link_to t('static_pages.footer.derose_for_leaders.all_over_the_world_html'), net_path, class: "inner-footer-link"%>
            </div>
          </div>
          <div class="col-md-4 footer-inner-column">
            <div class="after-title gold-color inner-footer-title"><%= t('static_pages.footer.testimonials.title') %></div>
            <div class="inner-footer-content">
              <%= link_to t('static_pages.footer.testimonials.enterprises'), enterprise_testimonials_path, class: "inner-footer-link"%>
              <%= link_to t('static_pages.footer.testimonials.institutions'), institution_testimonials_path, class: "inner-footer-link"%>
            </div>
          </div>
            <div class="col-md-4">
              <div class="after-title gold-color inner-footer-title footer-inner-column ">
                <%= t('static_pages.footer.enterprises.title') %>
              </div>
              <div class="inner-footer-content">
                <%= link_to t('static_pages.footer.enterprises.training'), intense_training_path, class: "inner-footer-link"%>
                <%= link_to t('static_pages.footer.enterprises.talks'), extensive_training_path, class: "inner-footer-link"%>
                <%= link_to t('static_pages.footer.enterprises.workshop'), leader_coaching_path, class: "inner-footer-link"%>
              </div>
            </div>
        </div>
        <div class="row">
          <div class="col-md-4 footer-inner-column">
            <div class="after-title gold-color inner-footer-title"><%= t('static_pages.footer.articles.title') %></div>
            <div class="inner-footer-content">
              <%= link_to t('static_pages.footer.articles.leadership'), articles_url(category: "leadership"), class: "inner-footer-link" %>
              <%= link_to t('static_pages.footer.articles.high_performance'), articles_url(category: "high performance"), class: "inner-footer-link" %>
              <%= link_to t('static_pages.footer.articles.focus'), articles_url(category: "focus"), class: "inner-footer-link" %>
              <%= link_to t('static_pages.footer.articles.intuition'), articles_url(category: "intuition"), class: "inner-footer-link" %>
              <%= link_to t('static_pages.footer.articles.human_relationships'), articles_url(category: "human relationships"), class: "inner-footer-link" %>
              <%= link_to t('static_pages.footer.articles.quality_of_life'), articles_url(category: "quality of life"), class: "inner-footer-link" %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="after-title gold-color inner-footer-title"><%= t('static_pages.footer.friends.title') %></div>
            <div class="inner-footer-content">
              <%= link_to "Edgardo Caramella","http://www.blogdeedgardo.com.ar/", class: "inner-footer-link" %>
            </div>
          </div>
          <div class="col-md-4 footer-inner-column footer-contact-us">
              <div class="pull-right">
                <div class="follow-title">
                  <%= link_to t('static_pages.footer.contact_us'), contact_path %>
                </div>
                <div class="follow-title">
                  <%= link_to t('static_pages.footer.apply_now'), contact_path %>
                </div>
                <div class="follow-title">
                  <%= t('static_pages.footer.follow_us') %>
                </div>
                <div class="follow-logos">
                  <a href="" class="footer-logos facebook-logo">
                    <%= image_tag 'logo-fb.png' %>
                  </a>
                  <a href="" class="footer-logos  twitter-logo">
                    <%= image_tag 'logo-tw.png' %>
                  </a>
                  <a href="" class="footer-logos linkedin-logo">
                    <%= image_tag 'logo-ln.png' %>
                  </a>
                  <a href="" class="footer-logos youtube-logo">
                    <%= image_tag 'logo-yt.png' %>
                  </a>
                  <a href="" class="footer-logos google-logo">
                    <%= image_tag 'logo-gp.png' %>
                  </a>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row header-container">
    <div class="header-main-row">
      <div class="col-md-4 image-row" data-no-turbolink>
        <%= link_to root_path do %>
          <% locale_logo %>
        <% end %>
      </div>
      <div class="col-md-7 header-text-row">
        <%= render "layouts/languages" %>
        <div class="row">
          <div class="col-md-12 pull-right teaching-phrase">
            <span class="teaching-phrase-location">
              <%= t('static_pages.header.teaching_phrase') %>
            </span>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 pull-right countries-header">
            <%= raw t('static_pages.header.countries_html') %>
          </div>
        </div>
      </div>
      <div class="col-md-1">
      </div>
    </div>
  </div>
  <div class="row">
    <%= render "layouts/navbar" %>
  </div>
</div>

app/views/layouts/_languages.html.erb
<div class="row pull-right languages-row">
  <div class="table-responsive">
      <table>
        <tr>
          <td>
            <%= link_to url_for(locale: :fr) do %>
              <%= image_tag 'lang_fr.png', class: "center" %>
            <% end %>
          </td>
          <td>
            <%= link_to url_for(locale: :en) do %>
              <%= image_tag 'lang_usa.png', class: "center" %>
            <% end %>
          </td>
          <td>
            <%= link_to url_for(locale: :pt) do %>
              <%= image_tag 'lang_pt.png', class: "center" %>
            <% end %>
          </td>
          <td>
            <%= link_to url_for(locale: :es) do %>
              <%= image_tag 'lang_es.png', class: "center" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar hidden-xs my-affix" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header" data-no-turbolink>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
        <%= image_tag 'lis_logo.png', class: 'navbar-brand' %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <%= render 'layouts/navbar_links' %>
    </div><!-- /.navbar-collapse -->
    
  </div><!-- /.container-fluid -->
</div>

app/views/layouts/_navbar_links.html.erb
<ul class="nav navbar-nav">
  <li class="<%= 'active' if controller?('static_pages') && action?("derose_method", "our_consultors", "net") %> dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= t('static_pages.navbar.derose_for_leaders.title_html') %>
    </a>
    <ul class="dropdown-menu" data-no-turbolink>
      <li>
        <%= link_to t('static_pages.navbar.derose_for_leaders.derose_method_html'), derose_method_path%>
      </li>
      <li>
        <%= link_to t('static_pages.navbar.derose_for_leaders.personal_teachers'), our_consultors_path%>
      </a></li>
      <li>
        <%= link_to t('static_pages.navbar.derose_for_leaders.all_over_the_world_html'), net_path%>
      </a></li>
    </ul>
  </li>
  
  <li class="<%= 'active' if controller?('static_pages') && action?("individual_consultory", "group_consultory") %> dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= t('static_pages.navbar.programs.title_html') %><b class="caret"></b>
    </a>
    <ul class="dropdown-menu" data-no-turbolink>
      <% if false %>
        <li class="navbar-non-clickable"><%= t('static_pages.navbar.programs.individuals.title') %></li>
        <li>
          <%= link_to t('static_pages.navbar.programs.individuals.training'), individual_consultory_path(:q => "3")+"#training"%>
        </li>
        <li>
          <%= link_to t('static_pages.navbar.programs.individuals.personal_teaching'), (individual_consultory_path(:q => "1")+"#personal")%>
        </li>
        <li>
          <%= link_to t('static_pages.navbar.programs.individuals.consulting'), individual_consultory_path(:q => "2")+"#consultory"%>
        </li>
        <li class="navbar-non-clickable"><%= t('static_pages.navbar.programs.enterprises.title') %></li>
      <% end %>
      <li>
        <%= link_to t('static_pages.navbar.programs.enterprises.training'), intense_training_path %>
      </li>
      <li>
        <%= link_to t('static_pages.navbar.programs.enterprises.talks'), extensive_training_path %>
      </li>
      <li>
        <%= link_to t('static_pages.navbar.programs.enterprises.workshop'), leader_coaching_path %>
      </li>
      
    </ul>
    <!-- ul class="dropdown-menu">
      <li>
        <div class="row">
          <ul class="list-unstyled col-md-6">
            <li><a href="individual_consultory" class="gold-title"> PARA INDIVIDUOS </a></li>      
            <li><a tabindex="-1" href="individual_consultory#personal">Personal Teaching</a></li>
            <li><a tabindex="-1" href="individual_consultory#consultory">Consultoria</a></li>
            <li><a tabindex="-1" href="individual_consultory#training">Treinamento</a></li>
            <li><a tabindex="-1" href="individual_consultory">Investimentos</a></li>
          </ul>
          <ul class="list-unstyled col-md-6">
            <li><a href="group_consultory" class="gold-title"> PARA EMPRESAS </a></li>
            <li><a tabindex="-1" href="group_consultory">Small Group Teaching</a></li>
            <li><a tabindex="-1" href="group_consultory#training">Treinamento</a></li>
            <li><a tabindex="-1" href="group_consultory#talks">Palestra</a></li>
            <li><a tabindex="-1" href="group_consultory#workshop">Workshop</a></li>
          </ul>
        </div>
      </li>
    </ul -->
  </li>
  <% if false %>
    <li class="<%= 'active' if controller_name == 'programmes' %> dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        PROGRAMAS<b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li class="dropdown-submenu">
          <a tabindex="-1" href="#">PARA INDIVIDUOS</a>
          <ul class="dropdown-menu">
            <li><a tabindex="-1" href="#">Personal Teaching</a></li>
            <li><a tabindex="-1" href="#">Consultoria</a></li>
            <li><a tabindex="-1" href="#">Treinamento</a></li>
            <li><a tabindex="-1" href="#">Investimentos</a></li>
          </ul>
        </li>
        <li class="dropdown-submenu">
          <a tabindex="-1" href="#">PARA EMPRESAS</a>
          <ul class="dropdown-menu">
            <li><a tabindex="-1" href="#">Small Group Teaching</a></li>
            <li><a tabindex="-1" href="#">Treinamento</a></li>
            <li><a tabindex="-1" href="#">Palestra</a></li>
            <li><a tabindex="-1" href="#">Workshop</a></li>
            <li><a tabindex="-1" href="#">Investimentos</a></li>
          </ul>
        </li>
      <% end %>
  </li>
  <li class="<%= 'active' if controller?('static_pages') && action?("enterprise_testimonials", "institution_testimonials") %> dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= t('static_pages.navbar.testimonials.title_html') %><b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li>
        <%= link_to t('static_pages.navbar.testimonials.enterprises'), enterprise_testimonials_path%>
      </li>
      <li>
        <%= link_to t('static_pages.navbar.testimonials.institutions'), institution_testimonials_path%>
      </li>
    </ul>
  </li>
  <li class="<%= 'active' if controller?('static_pages') && action?("articles") %> dropdown">
    <%= link_to t('static_pages.navbar.articles.title_html'), articles_path %>
    
    <!-- ul class="dropdown-menu">
      <li><a href="#">Liderança</a></li>
      <li><a href="#">Alta Produtividade</a></li>
      <li><a href="#">Foco</a></li>
      <li><a href="#">Intuição Aplicada</a></li>
      <li><a href="#">Relação Interpessoal</a></li>
      <li><a href="#">Qualidade de vida</a></li>
    </ul -->
  </li>
  <li class="<%= 'active' if controller?('static_pages') && action?("contact", "apply") %> dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= t('static_pages.navbar.contact_type.title_html') %><b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li>
        <%= link_to t('static_pages.navbar.contact_type.contact'), contact_path %>
      </li>
      <!-- li><a href="apply">Candidatura</a></li -->
    </ul>
  </li>
</ul>

app/views/layouts/_navbar_mobile.html.erb
<div class="navbar navbar-fixed-top my-affix visible-xs" role="navigation" id="slide-nav">
  <div class="container">
   <div class="navbar-header">
    <a class="navbar-toggle">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
     </a>
    <a class="navbar-brand" href="#"></a>
   </div>
   <div id="slidemenu">
    <%= render 'layouts/navbar_mobile_links' %>
   </div>
  </div>
 </div>

app/views/layouts/_navbar_mobile_links.html.erb
<ul class="nav navbar-nav mobile-navbar">
  <li class="">
    <a href="#" class="" data-toggle="">
      <%= t('static_pages.navbar.derose_for_leaders.title_html') %>
    </a>
    <ul class="" data-no-turbolink>
      <li>
        <%= link_to t('static_pages.navbar.derose_for_leaders.derose_method_html'), derose_method_path%>
      </li>
      <li>
        <%= link_to t('static_pages.navbar.derose_for_leaders.personal_teachers'), our_consultors_path%>
      </a></li>
      <li>
        <%= link_to t('static_pages.navbar.derose_for_leaders.all_over_the_world_html'), net_path%>
      </a></li>
    </ul>
  </li>

  <li class="">
    <a href="#" class="" data-toggle="">
      <%= t('static_pages.navbar.programs.title_html') %><b class="caret"></b>
    </a>
    <ul class="" data-no-turbolink>
      <li>
        <%= link_to t('static_pages.navbar.programs.enterprises.training'), intense_training_path %>
      </li>
      <li>
        <%= link_to t('static_pages.navbar.programs.enterprises.talks'), extensive_training_path %>
      </li>
      <li>
        <%= link_to t('static_pages.navbar.programs.enterprises.workshop'), leader_coaching_path %>
      </li>

    </ul>
  </li>
  <li class="">
    <a href="#" class="" data-toggle="">
      <%= t('static_pages.navbar.testimonials.title_html') %><b class="caret"></b>
    </a>
    <ul class="">
      <li>
        <%= link_to t('static_pages.navbar.testimonials.enterprises'), enterprise_testimonials_path%>
      </li>
      <li>
        <%= link_to t('static_pages.navbar.testimonials.institutions'), institution_testimonials_path%>
      </li>
    </ul>
  </li>
  <li class="">
    <%= link_to t('static_pages.navbar.articles.title_html'), articles_path %>
  </li>
  <li class="">
    <a href="#" class="" data-toggle="">
      <%= t('static_pages.navbar.contact_type.title_html') %><b class="caret"></b>
    </a>
    <ul class="">
      <li>
        <%= link_to t('static_pages.navbar.contact_type.contact'), contact_path %>
      </li>
    </ul>
  </li>
</ul>

app/views/layouts/_normal_toolbar.html.erb
<div id="wysihtml5-toolbar" style="display: none;">
  <a data-wysihtml5-command="bold" title="CTRL+B" class="btn btn-default"><span class="glyphicon glyphicon-bold" aria-hidden="true"></span></a>
  <a data-wysihtml5-command="italic" title="CTRL+I" class="btn btn-default"><span class="glyphicon glyphicon-italic" aria-hidden="true"></span></a>
  <a data-wysihtml5-command="createLink" class="btn btn-default"><span class="glyphicon glyphicon-link" aria-hidden="true"></span></a>
  <a data-wysihtml5-command="insertImage" class="btn btn-default"><span class="glyphicon glyphicon-picture" aria-hidden="true"></span></a>
  <a data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h1" class="btn btn-default">h1</a>
  <a data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h2" class="btn btn-default">h2</a>
  <a data-wysihtml5-command="insertUnorderedList" class="btn btn-default"><span class="glyphicon glyphicon-list" aria-hidden="true"></span></a>
  <a data-wysihtml5-command="insertOrderedList" class="btn btn-default"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span></a>
  <a data-wysihtml5-command="undo" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span></a>
  <a data-wysihtml5-command="redo" class="btn btn-default"><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span></a>
  <a data-wysihtml5-command="insertSpeech" class="btn btn-default">speech</a>
  <a data-wysihtml5-action="change_view" class="btn btn-default"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>
  
  <div data-wysihtml5-dialog="createLink" style="display: none;">
    <label>
      Link:
      <input data-wysihtml5-dialog-field="href" value="http://">
    </label>
    <a data-wysihtml5-dialog-action="save">OK</a>&nbsp;<a data-wysihtml5-dialog-action="cancel">Cancel</a>
  </div>
  
  <div data-wysihtml5-dialog="insertImage" style="display: none;">
    <label>
      Image:
      <input data-wysihtml5-dialog-field="src" value="http://">
    </label>
    <label>
      Align:
      <select data-wysihtml5-dialog-field="className">
        <option value="">default</option>
        <option value="wysiwyg-float-left">left</option>
        <option value="wysiwyg-float-right">right</option>
      </select>
    </label>
    <a data-wysihtml5-dialog-action="save">OK</a>&nbsp;<a data-wysihtml5-dialog-action="cancel">Cancel</a>
  </div>

</div>